In [267]:
import pandas as pd 
df = pd.read_excel(r"C:\Users\akash\Downloads\PYTHON\Alex_course\Customer Call List.xlsx")

In [268]:
df.drop_duplicates(inplace= True)

In [269]:
# remove column that are not required 
df = df.drop(columns='Not_Useful_Column')

In [270]:
# clean last name column 
#df.Last_Name = df.Last_Name.str.strip('...')
#df.Last_Name = df.Last_Name.str.strip('/')
#df.Last_Name = df.Last_Name.str.strip('_')

df.Last_Name = df.Last_Name.str.strip('123/_.!@#%^&*(_=+')

In [271]:
# keep letter and number and remove everything else 
df.Phone_Number = df['Phone_Number'].str.replace('[^0-9]', '', regex= True)

In [272]:

# convert all values to string
df['Phone_Number'] = df['Phone_Number'].apply(lambda x: str(x))

# now make it in format 000-000-0000

df.Phone_Number = df.Phone_Number.apply(lambda y : y[0:3]+'-'+ y[3:6]+'-'+ y[6:10])

In [273]:
# now remove null NA NAN and any other null values
df.Phone_Number.str.replace('[^-0-9]', '', regex= True)
df.Phone_Number = df.Phone_Number.str.replace('nan', '', regex= True)

In [274]:
# NOW split the Address column and make a new - PINCODE column 

df[['Street_Address', 'City', 'Pin_Code']] = df['Address'].str.split(',', n=2, expand= True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,City,Pin_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,93 West Main Street,None,None
2,1003,Walter,White,--,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,--,1209 South Street,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,--,123 Middle Earth,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,--,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,--,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,--,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,--,N/a,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,None

In [275]:
df.drop(columns = 'Address', inplace= True)

In [276]:
df['Paying Customer'] = df['Paying Customer'].replace({'YES': 'Y', 'Yes' : 'Y', 'No': 'N', 'no' : 'N'})
df['Paying Customer'] = df['Paying Customer'].replace({'Y': 'YES', 'N' : 'NO'})
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,City,Pin_Code
0,1001,Frodo,Baggins,123-545-5421,YES,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,NO,Yes,93 West Main Street,None,None
2,1003,Walter,White,--,NO,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,YES,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,YES,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,YES,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,--,NO,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,NO,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,--,YES,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,YES,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,--,YES,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,--,YES,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,YES,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,YES,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,NO,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,NO,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,YES,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,--,YES,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,--,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,YES,N,910 Tatooine Road,Tatooine,None

In [277]:
df['Do_Not_Contact'] = df['Do_Not_Contact'].replace({'Yes': 'Y', 'No': 'N'})
df['Do_Not_Contact'] = df['Do_Not_Contact'].replace({'Y': 'YES', 'N': 'NO'})

In [278]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,City,Pin_Code
0,1001,Frodo,Baggins,123-545-5421,YES,NO,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,NO,YES,93 West Main Street,None,None
2,1003,Walter,White,--,NO,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,YES,YES,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,YES,NO,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,YES,YES,768 City Parkway,None,None
6,1007,Jeff,Winger,--,NO,NO,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,NO,NO,98 Clue Drive,None,None
8,1009,Gandalf,NaN,--,YES,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,YES,NO,25th Main Street,New York,None
10,1011,Samwise,Gamgee,--,YES,NO,612 Shire Lane,Shire,None
11,1012,Harry,Potter,--,YES,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,YES,NO,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,YES,NO,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,NO,NO,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,NO,NO,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,YES,NO,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,--,YES,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,--,N/a,YES,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,YES,NO,910 Tatooine Road,Tatooine,None

In [279]:
df = df.replace('N/a', '--')

# You cannot replace NaN you have to fill it 
df = df.fillna('--')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,City,Pin_Code
0,1001,Frodo,Baggins,123-545-5421,YES,NO,123 Shire Lane,Shire,--
1,1002,Abed,Nadir,123-643-9775,NO,YES,93 West Main Street,--,--
2,1003,Walter,White,--,NO,--,298 Drugs Driveway,--,--
3,1004,Dwight,Schrute,123-543-2345,YES,YES,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,YES,NO,123 Dragons Road,--,--
5,1006,Ron,Swanson,304-762-2467,YES,YES,768 City Parkway,--,--
6,1007,Jeff,Winger,--,NO,NO,1209 South Street,--,--
7,1008,Sherlock,Holmes,876-678-3469,NO,NO,98 Clue Drive,--,--
8,1009,Gandalf,--,--,YES,--,123 Middle Earth,--,--
9,1010,Peter,Parker,123-545-5421,YES,NO,25th Main Street,New York,--
10,1011,Samwise,Gamgee,--,YES,NO,612 Shire Lane,Shire,--
11,1012,Harry,Potter,--,YES,--,2394 Hogwarts Avenue,--,--
12,1013,Don,Draper,123-543-2345,YES,NO,2039 Main Street,--,--
13,1014,Leslie,Knope,876-678-3469,YES,NO,343 City Parkway,--,--
14,1015,Toby,Flenderson,304-762-2467,NO,NO,214 HR Avenue,--,--
15,1016,Ron,Weasley,123-545-5421,NO,NO,2395 Hogwarts Avenue,--,--
16,1017,Michael,Scott,123-643-9775,YES,NO,121 Paper Avenue,Pennsylvania,--
17,1018,Clark,Kent,--,YES,--,3498 Super Lane,--,--
18,1019,Creed,Braton,--,--,YES,--,--,--
19,1020,Anakin,Skywalker,876-678-3469,YES,NO,910 Tatooine Road,Tatooine,--

In [ ]:
# filter rows and remove DO NOT CONTACT = YES 
#for i in df.index:
#    if(df.loc[i,'Do_Not_Contact'] == 'YES'):
#        df.drop(index= i, inplace= True)

In [282]:
df = df[df.Do_Not_Contact != "YES"]

#df = df[df['Do_Not_Contact'] != 'YES']

In [287]:
# REMOVE ROWS with NO Phone Nos

df =df[df.Phone_Number != '--']
df.reset_index(drop= True)

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,City,Pin_Code
0,1001,Frodo,Baggins,123-545-5421,YES,NO,123 Shire Lane,Shire,--
1,1005,Jon,Snow,876-678-3469,YES,NO,123 Dragons Road,--,--
2,1008,Sherlock,Holmes,876-678-3469,NO,NO,98 Clue Drive,--,--
3,1010,Peter,Parker,123-545-5421,YES,NO,25th Main Street,New York,--
4,1013,Don,Draper,123-543-2345,YES,NO,2039 Main Street,--,--
5,1014,Leslie,Knope,876-678-3469,YES,NO,343 City Parkway,--,--
6,1015,Toby,Flenderson,304-762-2467,NO,NO,214 HR Avenue,--,--
7,1016,Ron,Weasley,123-545-5421,NO,NO,2395 Hogwarts Avenue,--,--
8,1017,Michael,Scott,123-643-9775,YES,NO,121 Paper Avenue,Pennsylvania,--
9,1020,Anakin,Skywalker,876-678-3469,YES,NO,910 Tatooine Road,Tatooine,--